services:
  - type: web
    name: bellustore-backend
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: bellustore-db
          property: connectionString
    autoDeploy: true

databases:
  - name: bellustore-db
    databaseName: bellustore
    user: bellustore
    plan: starter
    region: oregon
    postgresMajorVersion: 15